name: Codacy Analysis

on:
  push:
    branches: [main, Trunk, bugfix]
  pull_request:
    branches: [main, Trunk, bugfix]

jobs:
  codacy-analysis:
    name: Codacy Analysis (linters + Analysis CLI)
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (needed for Codacy Analysis CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install linters and tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pylint bandit radon

      - name: Run linters and generate reports
        run: |
          # Ruff JSON
          ruff check . --format=json > ruff-report.json || true
          # Pylint JSON (runs only on tracked python files)
          pylint -f json $(git ls-files "*.py") > pylint-report.json || true
          # Bandit security scan (JSON)
          bandit -r . -f json -o bandit-report.json || true
          # Radon cyclomatic complexity in JSON
          radon cc -j . > radon-cc.json || true

      - name: Download Codacy Analysis CLI
        run: |
          # We try to download the latest release artifact using the conventional
          # GitHub "latest/download" URL. If your project requires a specific
          # CLI version, replace this URL with the stable release you want.
          CLI_URL="https://github.com/codacy/codacy-analysis-cli/releases/latest/download/codacy-analysis-cli.jar"
          echo "Downloading Codacy Analysis CLI from $CLI_URL"
          curl -sL -o codacy-analysis-cli.jar "$CLI_URL"
          ls -lah codacy-analysis-cli.jar

      - name: Run Codacy Analysis CLI
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          # Assumptions/notes:
          # - The CLI jar was downloaded above. If the release asset name differs
          #   or the URL is not valid anymore, update the download step.
          # - The exact CLI flags may vary between CLI versions. Adjust as needed.
          echo "Running Codacy Analysis CLI (it will collect/upload analysis results)"
          java -jar codacy-analysis-cli.jar analyze \
            --project-token "$CODACY_PROJECT_TOKEN" \
            --commit-uuid "${{ github.sha }}" \
            --branch "${{ github.ref }}" \
            --path . || true

      - name: Upload reports as workflow artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: codacy-analysis-reports
          path: |
            ruff-report.json
            pylint-report.json
            bandit-report.json
            radon-cc.json
